name: vector_svg
description: "A new Flutter package project."
publish_to: none
resolution: workspace
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_graphics: ^1.1.11+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
