// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkVhkpJ-tNhuVgg9luXthFUmn-Xk1t89k',
    appId: '1:488601416488:web:45e8e48a83cce791cf161d',
    messagingSenderId: '488601416488',
    projectId: 'test-c978e',
    authDomain: 'test-c978e.firebaseapp.com',
    storageBucket: 'test-c978e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjgd_GgsGomaCXFXfN27G6a8YbXq9Tdp4',
    appId: '1:488601416488:ios:127d3cec2ba3eb61cf161d',
    messagingSenderId: '488601416488',
    projectId: 'test-c978e',
    storageBucket: 'test-c978e.firebasestorage.app',
    iosBundleId: 'com.example.timeLogger',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjgd_GgsGomaCXFXfN27G6a8YbXq9Tdp4',
    appId: '1:488601416488:ios:127d3cec2ba3eb61cf161d',
    messagingSenderId: '488601416488',
    projectId: 'test-c978e',
    storageBucket: 'test-c978e.firebasestorage.app',
    iosBundleId: 'com.example.timeLogger',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASKyys7Oyp_VsTD3qD_PHPe78uATC-P8M',
    appId: '1:488601416488:android:cd7638fb72086c59cf161d',
    messagingSenderId: '488601416488',
    projectId: 'test-c978e',
    storageBucket: 'test-c978e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkVhkpJ-tNhuVgg9luXthFUmn-Xk1t89k',
    appId: '1:488601416488:web:36e2ccd80a474e86cf161d',
    messagingSenderId: '488601416488',
    projectId: 'test-c978e',
    authDomain: 'test-c978e.firebaseapp.com',
    storageBucket: 'test-c978e.firebasestorage.app',
  );

}